### ISSUE TITLE
Typo in Simple Card Agreement -- should refer to section 12

### ISSUE THREAD

**Issue by GuyPaddock** [SimpleFinance/policies#15]
Hello! 

While reviewing the "BBVA Compass Simple Visa Card Agreement", I noticed that section 10 currently indicates that customers are liable for all transactions except for what's described in section 13. I believe this should say "section 12", since section 13 refers to Simple's liability for transfers, while section 12 describes the customer's liability if a card is lost or stolen.

https://github.com/SimpleFinance/policies/blob/4338ed9a28b2ce8ed8bfbe6cc826918e311c6152/simple-card-agreement.html.erb#L107

**Comment by ewasik** [comment]
Fixed in the most recent update to the Card Agreement. 

https://github.com/SimpleFinance/policies/commit/316933965bc6b22e09acccd0c39b6cf22c5cf567

Thanks very much for pointing this out :)
